version: '3.9' 

services:

  client:
    build:
      context: src/client
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./src/client:/client
      - ./src/client/public:/client/public
      - node_modules_client:/client/node_modules

  api:
    depends_on:
      - db
      - redis
    links:
      - db
    build:
      context: src/api
      target: api
    env_file:
      .env
    ports:
      - 5000:5000
    volumes:
      - ./src/api:/api
      - ./src/client/public:/client/public
      - node_modules_api:/api/node_modules

  db:
    image: mariadb:10.8
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    ports:
    - 3306:3306
  
  prisma:
    build:
      context: src/api
      target: prisma
    volumes:
      - db:/var/lib/mysql
      - ./src/api/src/prisma:/api/src/prisma
    ports:
      - 5555:5555
    environment:
      DATABASE_URL: ${DATABASE_URL}

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD} 
    volumes: 
      - redis:/data
  
volumes:
  db:
  node_modules_api:
  node_modules_client:
  redis: