version: '3.9' 

services:

  client:
    build:
      context: src/client
    ports:
      - 3000:3000
    volumes:
      - ./src/client:/client
      - notused_client:/client/node_modules
    networks:
      internal:

  api:
    depends_on:
      - db
      - redis
    links:
      - db
    build:
      context: src/api
      target: api
    env_file:
      .env
    ports:
      - 5000:5000
    volumes:
      - ./src/api:/api
      - notused_api:/api/node_modules
    networks:
      internal:
      shared:

  db:
    image: mariadb:10.8
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    ports:
    - 3306:3306
    networks:
      internal:

  prisma:
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    build:
      context: src/api
      target: prisma
    volumes:
      - db:/var/lib/mysql
      - ./src/api/src/prisma:/api/src/prisma
    ports:
      - 5555:5555
    networks:
      internal:

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD} 
    volumes: 
      - redis:/data
    networks:
      internal:

volumes:
  db:
  redis:
  notused_client:
  notused_api:

networks:
  internal:
  shared:
    name: shared